"use client";

import Link from "next/link";
import { useRef, useState } from "react";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { ArrowRight, ArrowUpRight, ArrowsClockwise, CaretDown, ChartDonut, CheckCircle, Coins, Compass, Copy, Cube, Database, Fingerprint, GitBranch, List, LockKey, Pulse, ShieldCheck, TrendUp, UsersThree, Wallet, X } from "@phosphor-icons/react";
import { TokenETH, TokenSOL, TokenUSDC, TokenUSDT, TokenWBTC } from "@web3icons/react";
import styles from "./styles/landingv3.module.css";

gsap.registerPlugin(useGSAP, ScrollTrigger);

type StrategyType = "Index" | "Spot" | "Perpetual";
type Farm = { id: string; name: string; type: StrategyType; manager: string; source: string; pair: string; apy: string; tvl: string; network: "Base" | "Ethereum" | "Arbitrum"; risk: "Low" | "Moderate" | "High"; capacity: string; lpCount: number; status: string; assets: readonly string[]; history: readonly number[] };

const farms: Farm[] = [
  { id: "eth-neutral", name: "ETH Delta Neutral", type: "Perpetual", manager: "Northstar Capital", source: "Funding-rate capture", pair: "ETH / USDC", apy: "14.8%", tvl: "$2.84M", network: "Arbitrum", risk: "High", capacity: "$7.5M", lpCount: 184, status: "Active demo", assets: ["ETH", "USDC"], history: [22,31,27,44,39,55,61,58,72,81] },
  { id: "blue-chip", name: "Blue Chip Index", type: "Index", manager: "Atlas Research", source: "Rules-based rebalancing", pair: "ETH / WBTC / SOL", apy: "12.6%", tvl: "$1.65M", network: "Ethereum", risk: "Moderate", capacity: "$5M", lpCount: 126, status: "Active demo", assets: ["ETH", "WBTC", "SOL"], history: [25,22,32,38,35,48,53,67,64,79] },
  { id: "stable-yield", name: "Stablecoin Yield", type: "Spot", manager: "Lattice Labs", source: "Lending yield", pair: "USDC / USDT", apy: "7.2%", tvl: "$920K", network: "Base", risk: "Low", capacity: "$3M", lpCount: 89, status: "Active demo", assets: ["USDC", "USDT"], history: [18,23,29,33,41,44,51,57,63,69] },
  { id: "btc-carry", name: "BTC Carry", type: "Perpetual", manager: "Meridian Digital", source: "Basis and funding", pair: "WBTC / USDC", apy: "10.9%", tvl: "$740K", network: "Arbitrum", risk: "Moderate", capacity: "$2.5M", lpCount: 72, status: "Capacity open", assets: ["WBTC", "USDC"], history: [28,35,31,47,52,49,58,63,71,76] },
  { id: "diversified-stables", name: "Diversified Stables", type: "Spot", manager: "Signal Works", source: "Multi-protocol lending", pair: "USDC / USDT", apy: "8.4%", tvl: "$610K", network: "Base", risk: "Low", capacity: "$4M", lpCount: 64, status: "Active demo", assets: ["USDC", "USDT"], history: [26,29,34,38,45,51,55,60,65,73] },
  { id: "market-index", name: "Crypto Market Index", type: "Index", manager: "Arc Seven", source: "Market-cap allocation", pair: "WBTC / ETH / SOL", apy: "11.3%", tvl: "$1.12M", network: "Ethereum", risk: "Moderate", capacity: "$6M", lpCount: 103, status: "Active demo", assets: ["WBTC", "ETH", "SOL"], history: [21,27,34,31,43,50,59,62,70,78] },
];

const activities = [
  { icon: ArrowsClockwise, action: "Manager rebalanced ETH allocation", value: "+4.8%", meta: "Block 24,918,304", network: "Base", tx: "0x7cf6…29e7", time: "2m ago" },
  { icon: Wallet, action: "LP deposited", value: "75,000 USDC", meta: "Block 24,918,261", network: "Base", tx: "0xa13d…91bf", time: "8m ago" },
  { icon: TrendUp, action: "Funding payment received", value: "$2,480", meta: "Block 284,190,441", network: "Arbitrum", tx: "0x82b1…e043", time: "21m ago" },
  { icon: GitBranch, action: "Position hedge adjusted", value: "0.48 ETH", meta: "Block 284,190,102", network: "Arbitrum", tx: "0xe219…45a7", time: "34m ago" },
  { icon: ArrowUpRight, action: "Withdrawal processed", value: "18,500 USDC", meta: "Block 24,917,884", network: "Base", tx: "0xc841…8bd2", time: "51m ago" },
];

const yieldModels = {
  Index: { icon: ChartDonut, summary: "Rules turn a capital mandate into a transparent portfolio.", flow: ["Capital", "Portfolio allocation", "Rules-based rebalance", "Portfolio return"], returns: "Asset performance and disciplined rebalancing", risks: "Market movement and allocation drift", liquidity: "Portfolio settlement window", networks: "Ethereum · Base" },
  Spot: { icon: Coins, summary: "Capital enters productive spot markets without hiding its route.", flow: ["Capital", "Lending or LP", "Yield and fees", "Compounding"], returns: "Borrow interest, trading fees and incentives", risks: "Protocol, liquidity and smart-contract risk", liquidity: "Underlying protocol liquidity", networks: "Base · Ethereum" },
  Perpetual: { icon: TrendUp, summary: "Collateral, hedge and funding are managed as one visible system.", flow: ["Collateral", "Market position", "Hedge", "Funding and P&L"], returns: "Funding payments and market-neutral basis", risks: "Leverage, liquidation and execution risk", liquidity: "Venue depth and margin buffer", networks: "Arbitrum" },
} as const;

const assetIcons = { ETH: TokenETH, USDC: TokenUSDC, USDT: TokenUSDT, WBTC: TokenWBTC, SOL: TokenSOL } as const;

export function LandingV3Root({ segments = ["home"] }: { segments?: string[] }) {
  const page = segments[0] || "home";
  const [mobile, setMobile] = useState(false);
  return <main className={styles.root}>
    <Nav mobile={mobile} setMobile={setMobile} />
    {page === "home" && <Home />}{page === "yield" && <Yield />}{page === "farms" && <Farms />}{page === "farm-details" && <FarmDetails farmId={segments[1]} />}{page === "networks" && <Networks />}
    <Footer />
  </main>;
}

function Nav({ mobile, setMobile }: { mobile: boolean; setMobile: (value: boolean) => void }) {
  return <nav className={styles.nav} aria-label="Dexponent navigation"><Brand /><div className={`${styles.navLinks} ${mobile ? styles.open : ""}`}><a href="/landingv3/home#strategies">Strategies</a><a href="/landingv3/home#for-lps">For LPs</a><a href="/landingv3/home#for-managers">For managers</a><a href="/landingv3/home#how-it-works">How it works</a><a href="/landingv3/home#network">Network</a><a href="/landingv3/home#resources">Resources</a></div><div className={styles.navActions}><Link className={styles.navSecondary} href="/landingv3/farms">Explore strategies</Link><Link className={styles.primary} href="/dbv3/farms/create">Launch a Farm <ArrowUpRight size={16} /></Link><button className={styles.mobileMenu} aria-label={mobile ? "Close navigation" : "Open navigation"} onClick={() => setMobile(!mobile)}>{mobile ? <X size={20} /> : <List size={20} />}</button></div></nav>;
}

function Home() {
  const homeRef = useRef<HTMLDivElement>(null);
  useGSAP(() => {
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    gsap.fromTo("[data-hero]", { y: 36, opacity: 0 }, { y: 0, opacity: 1, duration: 1.05, stagger: .09, ease: "power3.out" });
    gsap.utils.toArray<HTMLElement>("[data-reveal]").forEach((element) => gsap.fromTo(element, { y: 42, opacity: 0 }, { y: 0, opacity: 1, duration: .85, ease: "power3.out", scrollTrigger: { trigger: element, start: "top 84%" } }));
    gsap.fromTo("[data-scrub] span", { opacity: .14 }, { opacity: 1, stagger: .08, scrollTrigger: { trigger: "[data-scrub]", start: "top 75%", end: "bottom 45%", scrub: .7 } });
    const media = gsap.matchMedia(); media.add("(min-width: 1000px)", () => ScrollTrigger.create({ trigger: `.${styles.yieldSection}`, start: "top 96px", end: "bottom bottom", pin: `.${styles.yieldIntro}`, pinSpacing: false })); return () => media.revert();
  }, { scope: homeRef });
  return <div ref={homeRef} className={styles.home}>
    <section className={styles.hero}><div className={styles.heroAtmosphere} aria-hidden="true" /><div className={styles.heroCopy}><p className={styles.eyebrow} data-hero>Onchain managed capital</p><h1 data-hero>Capital, managed <em>onchain.</em></h1><p className={styles.heroLead} data-hero>Dexponent turns Index, Spot and Perpetual strategies into transparent managed products—so managers can operate capital and LPs can see how it moves.</p><div className={styles.heroActions} data-hero><Link className={styles.primaryLarge} href="/landingv3/farms">Explore strategies <ArrowRight size={18} /></Link><Link className={styles.secondaryLarge} href="/dbv3/farms/create">Launch a Farm <ArrowUpRight size={18} /></Link><a className={styles.textAction} href="#how-it-works">How Dexponent works <CaretDown size={15} /></a></div></div><CapitalFlowVisual /></section>
    <ProtocolStrip />
    <section className={styles.shift} id="how-it-works"><div className={styles.shiftIntro} data-reveal><p className={styles.eyebrow}>A simpler operating model</p><h2 data-scrub>{"Onchain strategies are fragmented. Dexponent makes them investable.".split(" ").map((word,index)=><span key={`${word}-${index}`}>{word} </span>)}</h2></div><div className={styles.shiftGrid} data-reveal><div className={styles.fragmented}><small>Without Dexponent</small>{["Find protocols","Bridge capital","Track positions","Watch risk","Exit manually"].map((item,index)=><div key={item}><span>{String(index+1).padStart(2,"0")}</span>{item}</div>)}</div><div className={styles.shiftCore}><BrandMark /><strong>One transparent product layer</strong><p>Discovery, allocation, operations and reporting share the same capital model.</p></div><div className={styles.unified}><small>With Dexponent</small>{["Discover","Compare","Allocate","Monitor"].map((item)=><div key={item}><CheckCircle size={18} weight="fill" />{item}</div>)}</div></div></section>
    <StrategyExplorer /><YieldMechanism /><AudienceExperience /><FarmCreation /><SystemSection /><ActivitySection /><NetworkSecurity />
    <section className={styles.future} data-reveal><p className={styles.eyebrow}>The shift is already underway</p><h2>Asset management is becoming programmable.</h2><div className={styles.futureFlow}>{["Traditional funds","Tokenized assets","Onchain strategies","Programmable management"].map((item,index)=><div key={item}><span>{item}</span>{index<3&&<ArrowRight size={18}/>}</div>)}</div><p>Dexponent is the infrastructure layer where investment rules, manager actions and LP capital meet onchain.</p></section>
    <section className={styles.managerCta} id="for-managers" data-reveal><div><p className={styles.eyebrow}>For strategy creators</p><h2>Build a strategy people can actually allocate to.</h2><p>Turn an investment thesis into a transparent onchain product, establish a track record and grow an LP community.</p></div><div className={styles.managerProfile}><div><span>NC</span><p><strong>Northstar Capital</strong><small>Verified demo manager</small></p></div><dl><div><dt>Managed capital</dt><dd>$2.84M</dd></div><div><dt>Track record</dt><dd>14 months</dd></div><div><dt>LPs</dt><dd>184</dd></div></dl></div><div className={styles.ctaRow}><Link className={styles.primaryLarge} href="/dbv3/farms/create">Launch a Farm <ArrowRight size={18}/></Link><a className={styles.secondaryLarge} href="https://docs.dexponent.com" target="_blank" rel="noreferrer">Manager documentation <ArrowUpRight size={18}/></a></div></section>
    <section className={styles.finalCta} data-reveal><div className={styles.finalNetwork} aria-hidden="true"><BrandMark />{[0,1,2,3,4,5].map((node)=><i key={node}/>)}</div><p className={styles.eyebrow}>Transparent by design</p><h2>The next generation of managed capital will live onchain.</h2><p>Explore transparent strategies or launch your own.</p><div><Link className={styles.primaryLarge} href="/landingv3/farms">Explore strategies</Link><Link className={styles.secondaryLarge} href="/dbv3/farms/create">Launch a Farm</Link></div></section>
  </div>;
}

function CapitalFlowVisual() { const move=(event:React.MouseEvent<HTMLDivElement>)=>{const bounds=event.currentTarget.getBoundingClientRect();event.currentTarget.style.setProperty("--mx",`${event.clientX-bounds.left}px`);event.currentTarget.style.setProperty("--my",`${event.clientY-bounds.top}px`)}; return <div className={styles.capitalVisual} onMouseMove={move} data-hero><div className={styles.cursorGlow}/><div className={`${styles.flowNode} ${styles.lpNode}`}><Wallet size={20}/><span>LP capital</span><strong>USDC</strong></div><svg className={styles.flowLines} viewBox="0 0 800 400" preserveAspectRatio="none" aria-hidden="true"><path d="M150 200 C260 200 260 200 350 200"/><path d="M450 200 C550 200 550 75 650 75"/><path d="M450 200 C550 200 550 200 650 200"/><path d="M450 200 C550 200 550 325 650 325"/><circle r="5"><animateMotion dur="3s" repeatCount="indefinite" path="M150 200 C260 200 260 200 350 200 C550 200 550 75 650 75"/></circle><circle r="5"><animateMotion begin=".8s" dur="3.3s" repeatCount="indefinite" path="M150 200 C260 200 260 200 350 200 C550 200 550 200 650 200"/></circle><circle r="5"><animateMotion begin="1.5s" dur="3.6s" repeatCount="indefinite" path="M150 200 C260 200 260 200 350 200 C550 200 550 325 650 325"/></circle></svg><div className={`${styles.flowNode} ${styles.engineNode}`}><BrandMark/><span>Dexponent engine</span><small>Rules · risk · reporting</small></div><div className={styles.routeNodes}><div><ChartDonut size={18}/><span>Index</span><small>Rules-based</small></div><div><Coins size={18}/><span>Spot</span><small>Yield markets</small></div><div><TrendUp size={18}/><span>Perpetual</span><small>Hedged markets</small></div></div><span className={styles.flowCaption}><Pulse size={15}/> Illustrative capital routing</span></div> }

function ProtocolStrip(){const stats=[["Illustrative TVL","$7.88M"],["Demo strategies","06"],["Demo managers","05"],["Networks","03"],["LP positions","638"],["30D volume","$4.21M"]];return <section className={styles.protocolStrip} aria-label="Illustrative protocol statistics"><div className={styles.demoFlag}><i/> Demo network snapshot</div><div className={styles.statTrack}>{[...stats,...stats].map(([label,value],index)=><div key={`${label}-${index}`}><strong>{value}</strong><span>{label}</span></div>)}</div></section>}

function StrategyExplorer(){const[filter,setFilter]=useState<"All"|StrategyType>("All");const[focus,setFocus]=useState(farms[0]);const filtered=filter==="All"?farms:farms.filter((farm)=>farm.type===filter);return <section className={styles.marketplace} id="strategies"><div className={styles.sectionHead} data-reveal><div><p className={styles.eyebrow}>Strategy marketplace</p><h2>Different engines for different return mandates.</h2></div><p>Compare the return source, liquidity, capacity and risk before opening a Farm profile.</p></div><div className={styles.filters} role="tablist" aria-label="Filter strategies">{(["All","Index","Spot","Perpetual"]as const).map((type)=><button key={type} role="tab" aria-selected={filter===type} onClick={()=>setFilter(type)}>{type}</button>)}</div><div className={styles.marketLayout} data-reveal><div className={styles.focusStrategy}><div className={styles.focusTop}><span><i/> {focus.status}</span><NetworkMark network={focus.network} withName/></div><div><AssetPair assets={focus.assets}/><p>{focus.type} Farm</p><h3>{focus.name}</h3><span>Managed by {focus.manager}</span></div><Sparkline values={focus.history}/><div className={styles.focusMetrics}><Metric label="Estimated APY" value={focus.apy}/><Metric label="Demo TVL" value={focus.tvl}/><Metric label="Capacity" value={focus.capacity}/><Metric label="Risk" value={focus.risk}/></div><p className={styles.returnSource}>Return source <strong>{focus.source}</strong></p><Link href={`/landingv3/farm-details/${focus.id}`}>Open Farm profile <ArrowUpRight size={16}/></Link></div><div className={styles.strategyList}>{filtered.map((farm)=><button key={farm.id} className={focus.id===farm.id?styles.activeStrategy:""} onMouseEnter={()=>setFocus(farm)} onFocus={()=>setFocus(farm)} onClick={()=>setFocus(farm)}><AssetPair assets={farm.assets.slice(0,2)}/><span><strong>{farm.name}</strong><small>{farm.manager} · {farm.source}</small></span><span><small>Est. APY</small><strong>{farm.apy}</strong></span><span><small>Demo TVL</small><strong>{farm.tvl}</strong></span><span className={styles.riskTag}>{farm.risk}</span><ArrowRight size={16}/></button>)}</div></div><Link className={styles.inlineAction} href="/landingv3/farms">Explore all strategies <ArrowRight size={16}/></Link></section>}

function YieldMechanism(){const[active,setActive]=useState<StrategyType>("Index");const model=yieldModels[active];const Icon=model.icon;return <section className={styles.yieldSection}><div className={styles.yieldIntro}><p className={styles.eyebrow}>Yield, explained</p><h2>Understand the return before the APY.</h2><p>Every Farm exposes the economic engine, constraints and risks behind its headline number.</p></div><div className={styles.yieldWorkspace} data-reveal><div className={styles.yieldTabs} role="tablist" aria-label="Yield mechanism">{(["Index","Spot","Perpetual"]as const).map((type)=><button key={type} role="tab" aria-selected={active===type} onClick={()=>setActive(type)}>{type}</button>)}</div><div className={styles.yieldTitle}><Icon size={30}/><div><p>{active} strategy</p><h3>{model.summary}</h3></div></div><div className={styles.mechanismFlow}>{model.flow.map((step,index)=><div key={step}><span>{String(index+1).padStart(2,"0")}</span><strong>{step}</strong>{index<model.flow.length-1&&<ArrowRight size={18}/>}</div>)}</div><dl className={styles.mechanismFacts}><div><dt>Return source</dt><dd>{model.returns}</dd></div><div><dt>Risk source</dt><dd>{model.risks}</dd></div><div><dt>Liquidity</dt><dd>{model.liquidity}</dd></div><div><dt>Networks</dt><dd>{model.networks}</dd></div></dl></div></section>}

function AudienceExperience(){const[audience,setAudience]=useState<"LP"|"Manager">("LP");return <section className={styles.audience} id="for-lps"><div className={styles.audienceToggle} role="tablist" aria-label="Choose product view"><button role="tab" aria-selected={audience==="LP"} onClick={()=>setAudience("LP")}>For LPs</button><button role="tab" aria-selected={audience==="Manager"} onClick={()=>setAudience("Manager")}>For managers</button></div><div className={styles.audienceCopy} data-reveal><p className={styles.eyebrow}>{audience==="LP"?"Decision-ready for LPs":"One system for managers"}</p><h2>{audience==="LP"?"Know what you're allocating to.":"Your strategy. One operating system."}</h2><p>{audience==="LP"?"See the return source, risk, liquidity and manager activity before capital enters a Farm.":"Create, deploy, raise and operate without building fund administration software from scratch."}</p><ul>{(audience==="LP"?["Discover and compare Farms","Understand risk and return","Track positions and liquidity","Review manager actions"]:["Configure strategy rules","Set fees and risk controls","Monitor exposure and LP flows","Rebalance with context"]).map((item)=><li key={item}><CheckCircle size={17} weight="fill"/>{item}</li>)}</ul></div>{audience==="LP"?<LPInterface/>:<ManagerInterface/>}</section>}
function LPInterface(){return <div className={styles.productUi} data-reveal><div className={styles.uiTop}><span>Portfolio overview</span><small><i/> Demo</small></div><div className={styles.balance}><p>Net position value</p><strong>$184,250.00</strong><span>+$8,412.40 <small>since allocation</small></span></div><div className={styles.allocation}>{[["ETH Delta Neutral",46,"$84,755"],["Blue Chip Index",34,"$62,645"],["Stablecoin Yield",20,"$36,850"]].map(([name,share,value])=><div key={name as string}><span><strong>{name}</strong><small>{value}</small></span><i><b style={{width:`${share}%`}}/></i><em>{share}%</em></div>)}</div><button>View all positions <ArrowRight size={15}/></button></div>}
function ManagerInterface(){return <div className={styles.productUi} data-reveal><div className={styles.uiTop}><span>Farm operations</span><small><i/> Active demo</small></div><div className={styles.managerFarm}><AssetPair assets={["ETH","USDC"]}/><div><small>Perpetual Farm</small><strong>ETH Delta Neutral</strong></div><span>14.8% <small>Est. APY</small></span></div><div className={styles.exposure}><div><span>Long spot</span><strong>$1.41M</strong><i style={{width:"72%"}}/></div><div><span>Short perp</span><strong>−$1.39M</strong><i style={{width:"69%"}}/></div><div><span>Net delta</span><strong>+0.8%</strong><i style={{width:"18%"}}/></div></div><div className={styles.managerActions}><button><ArrowsClockwise size={16}/> Rebalance</button><button>Review LP flows</button></div></div>}

function FarmCreation(){const steps=[{icon:Compass,title:"Choose a strategy type",copy:"Index, Spot or Perpetual."},{icon:GitBranch,title:"Configure capital rules",copy:"Assets, venues and allocation logic."},{icon:ShieldCheck,title:"Set risk and fees",copy:"Controls stay attached to the product."},{icon:Cube,title:"Deploy onchain",copy:"Review every parameter before publishing."},{icon:UsersThree,title:"Accept capital and operate",copy:"Track LP flows, exposure and performance."}];return <section className={styles.creation} data-reveal><div><p className={styles.eyebrow}>From thesis to product</p><h2>Build an investable Farm in one connected flow.</h2><Link className={styles.inlineAction} href="/dbv3/farms/create">Open the Farm builder <ArrowUpRight size={16}/></Link></div><div className={styles.creationPath}>{steps.map(({icon:Icon,title,copy},index)=><article key={title}><span>{String(index+1).padStart(2,"0")}</span><Icon size={24}/><h3>{title}</h3><p>{copy}</p>{index<steps.length-1&&<i/>}</article>)}</div></section>}
function SystemSection(){const pillars=[[Database,"One operating model","Index, Spot and Perpetual share one creation and management framework."],[Fingerprint,"Transparent capital","Positions, allocations and manager actions remain visible and attributable."],[UsersThree,"Manager-first infrastructure","Managers focus on strategy while Dexponent handles the operating layer."],[Compass,"Decision-ready for LPs","Return source, liquidity, risk and activity appear before allocation."],[GitBranch,"Programmable products","Strategy rules, fees and controls become part of the product itself."]]as const;return <section className={styles.system}><div className={styles.systemCore} data-reveal><div className={styles.orbit}><BrandMark/>{pillars.map(([Icon,title],index)=><span key={title} style={{"--index":index}as React.CSSProperties}><Icon size={19}/></span>)}</div><p>Dexponent core</p><h2>One system between strategy intent and onchain capital.</h2></div><div className={styles.systemList}>{pillars.map(([Icon,title,copy])=><article key={title} data-reveal><Icon size={22}/><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>}
function ActivitySection(){return <section className={styles.activity}><div className={styles.sectionHead} data-reveal><div><p className={styles.eyebrow}>Onchain activity</p><h2>Every strategy leaves a trail.</h2></div><p>Manager actions and LP capital movements remain visible. This feed uses illustrative demo events.</p></div><div className={styles.activityFeed} data-reveal>{activities.map(({icon:Icon,action,value,meta,network,tx,time})=><article key={`${action}-${time}`}><span className={styles.activityIcon}><Icon size={19}/></span><div><strong>{action}</strong><small>{meta} · {time}</small></div><b>{value}</b><span><NetworkMark network={network}/>{network}</span><code>{tx}</code><button aria-label={`Copy transaction hash ${tx}`}><Copy size={15}/></button></article>)}</div></section>}
function NetworkSecurity(){return <section className={styles.networkSecurity} id="network"><div className={styles.networkPanel} data-reveal><p className={styles.eyebrow}>Network coverage</p><h2>Built where strategies operate.</h2><p>Current demo experiences cover Base, Ethereum and Arbitrum. Availability varies by strategy.</p><div className={styles.networkMap}><div className={styles.mapCore}><BrandMark/></div>{["Base","Ethereum","Arbitrum"].map((network)=><div key={network} className={styles.mapNode}><NetworkMark network={network}/><strong>{network}</strong><small>{network==="Base"?"Beta network":"Demo support"}</small></div>)}</div></div><div className={styles.securityPanel} id="resources" data-reveal><ShieldCheck size={34}/><p className={styles.eyebrow}>Security and trust</p><h2>Controls users can inspect.</h2><ul><li><LockKey size={18}/> Non-custodial architecture</li><li><GitBranch size={18}/> Visible manager permissions</li><li><Pulse size={18}/> Onchain transaction history</li><li><ShieldCheck size={18}/> Risk controls attached to Farms</li></ul><a href="https://audits.hacken.io" target="_blank" rel="noreferrer">View Hacken audit reports <ArrowUpRight size={16}/></a><small>Digital assets involve risk. Demo performance is illustrative and returns are not guaranteed.</small></div></section>}

function Yield(){return <section className={styles.page}><PageHeading kicker="Yield intelligence" title="Understand where every return comes from." copy="Compare lending, liquidity, funding and allocation models with explicit risk and liquidity context."/><div className={styles.pageGrid}>{Object.entries(yieldModels).map(([title,item])=>{const Icon=item.icon;return <article key={title}><Icon size={27}/><h2>{title}</h2><p>{item.summary}</p><Link href="/landingv3/farms">View matching Farms <ArrowRight size={15}/></Link></article>})}</div></section>}
function Farms(){return <section className={styles.page}><PageHeading kicker="Strategy marketplace" title="Choose with more than a headline APY." copy="Compare return source, risk, liquidity, manager and network before opening the full Farm profile."/><FarmRows/></section>}
function FarmDetails({farmId}:{farmId?:string}){const farm=farms.find((item)=>item.id===farmId)||farms[0];return <section className={styles.page}><Link className={styles.back} href="/landingv3/farms">← All Farms</Link><div className={styles.detailHero}><div><AssetPair assets={farm.assets}/><span className={styles.eyebrow}>{farm.network} · {farm.type}</span><h1>{farm.name}</h1><p>{farm.source} managed by {farm.manager}. All figures on this profile are illustrative demo values.</p></div><Link className={styles.primaryLarge} href={`/dbv3/farms/manage?farm=${farm.id}`}>Open Farm workspace</Link></div><div className={styles.detailMetrics}><Metric label="Estimated APY" value={farm.apy}/><Metric label="Demo TVL" value={farm.tvl}/><Metric label="Risk" value={farm.risk}/><Metric label="LPs" value={String(farm.lpCount)}/></div><div className={styles.detailBody}><article><h2>Return source</h2><p>{farm.source}</p><div className={styles.detailFlow}><span>USDC capital</span><ArrowRight size={17}/><span>{farm.type} rules</span><ArrowRight size={17}/><span>{farm.pair}</span></div></article><article><h2>Risk context</h2><p>Returns can change. Capital remains exposed to market, protocol, liquidity and smart-contract risk.</p><Link href="/dbv3/farms/create">Create a similar Farm <ArrowUpRight size={15}/></Link></article></div></section>}
function Networks(){return <section className={styles.page}><PageHeading kicker="Network coverage" title="One operating model across supported ecosystems." copy="Current demo surfaces show Base, Ethereum and Arbitrum while keeping Farm and Position language consistent."/><div className={styles.pageGrid}>{["Base","Ethereum","Arbitrum"].map((network)=><article key={network}><NetworkMark network={network}/><h2>{network}</h2><p>{network==="Base"?"Current beta network.":"Available in the illustrative V3 strategy experience."}</p><CheckCircle size={18}/></article>)}</div></section>}
function FarmRows(){return <div className={styles.farmRows}>{farms.map((farm)=><Link href={`/landingv3/farm-details/${farm.id}`} key={farm.id}><AssetPair assets={farm.assets.slice(0,2)}/><span><strong>{farm.name}</strong><small>{farm.type} · {farm.source}</small></span><span><small>Manager</small><strong>{farm.manager}</strong></span><span><small>Est. APY</small><strong>{farm.apy}</strong></span><span><small>Demo TVL</small><strong>{farm.tvl}</strong></span><span className={styles.riskTag}>{farm.risk}</span><ArrowRight size={17}/></Link>)}</div>}
function PageHeading({kicker,title,copy}:{kicker:string;title:string;copy:string}){return <header className={styles.pageHeading}><p className={styles.eyebrow}>{kicker}</p><h1>{title}</h1><p>{copy}</p></header>}
function Metric({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function Sparkline({values}:{values:readonly number[]}){const points=values.map((value,index)=>`${(index/(values.length-1))*100},${100-value}`).join(" ");return <svg className={styles.sparkline} viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Illustrative 30 day performance trend"><defs><linearGradient id="spark-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#00e89a" stopOpacity=".28"/><stop offset="1" stopColor="#00e89a" stopOpacity="0"/></linearGradient></defs><polygon points={`0,100 ${points} 100,100`} fill="url(#spark-fill)"/><polyline points={points} fill="none" vectorEffect="non-scaling-stroke"/></svg>}
function Brand(){return <Link className={styles.brand} href="/landingv3/home" aria-label="Dexponent home"><img src="/brand/dexponent-mark.svg" alt=""/><span>Dexponent</span></Link>}
function BrandMark(){return <span className={styles.brandMark}><img src="/brand/dexponent-mark.svg" alt=""/></span>}
function AssetPair({assets}:{assets:readonly string[]}){return <span className={styles.assetPair}>{assets.map((asset)=>{const Token=assetIcons[asset as keyof typeof assetIcons];return <span key={asset} title={asset}>{Token?<Token variant="background" size={34}/>:asset}</span>})}</span>}
function NetworkMark({network,withName=false}:{network:string;withName?:boolean}){const src=network==="Base"?"/brand/chains/base.svg":network==="Ethereum"?"/brand/chains/ethereum.png":"/brand/chains/arbitrum.png";return <span className={styles.networkMark}><img src={src} alt=""/>{withName&&<small>{network}</small>}</span>}
function Footer(){return <footer className={styles.footer}><div className={styles.footerBrand}><Brand/><p>The operating layer for transparent onchain managed capital.</p><small>Base mainnet beta. Digital assets can lose all value. Returns and withdrawals are not guaranteed.</small></div><div><strong>Product</strong><Link href="/landingv3/farms">Strategies</Link><Link href="/landingv3/yield">Index</Link><Link href="/landingv3/yield">Spot</Link><Link href="/landingv3/yield">Perpetual</Link><Link href="/dbv3/dashboard">Dashboard</Link></div><div><strong>Managers</strong><Link href="/dbv3/farms/create">Launch Farm</Link><a href="https://docs.dexponent.com" target="_blank" rel="noreferrer">Documentation</a><a href="https://docs.dexponent.com" target="_blank" rel="noreferrer">Manager guide</a></div><div><strong>Resources</strong><a href="https://docs.dexponent.com" target="_blank" rel="noreferrer">Docs</a><a href="https://medium.com" target="_blank" rel="noreferrer">Blog</a><a href="https://audits.hacken.io" target="_blank" rel="noreferrer">Audits</a><a href="https://docs.dexponent.com" target="_blank" rel="noreferrer">Beta guide</a></div><div><strong>Legal</strong><a href="https://dexponent.com/terms" target="_blank" rel="noreferrer">Terms</a><a href="https://dexponent.com/privacy" target="_blank" rel="noreferrer">Privacy</a><a href="https://dexponent.com/risk-disclosure" target="_blank" rel="noreferrer">Risk disclosure</a></div><div className={styles.footerBottom}><span>© 2026 Dexponent</span><span>Demo data is clearly labeled and illustrative.</span></div></footer>}
